services:
  server:
    build: NeoForge-server
    image: neoforge-server:latest
    ports:
      - 25568:25565
    stdin_open: true # io
    volumes:
      - neoforge-data:/neoforge
    restart: unless-stopped

  backup:
    build: world-backup
    image: world-backup:latest
    volumes:
      - neoforge-data:/data
      - neoforge-world-bak:/bak
    restart: unless-stopped

volumes:
  neoforge-data:
  neoforge-world-bak:
